### PR TITLE
Neuron dashboard

### PR DESCRIPTION
**Pull request by freschri**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by freschri** [comment]
@elamaran11 could you please have a look at this and merge if ok? it is a dependency for the neuron pattern on observability. thanks

**Comment by elamaran11** [comment]
@freschri Please fix the GH action failures.

**Comment by freschri** [comment]
> @freschri Please fix the GH action failures.

done @elamaran11 please have a look

**Review by elamaran11 — APPROVED** [review]
LGTM

**Pull request merged**
