### PR TITLE
Add Kubernetes admin dashboards

### PR DESCRIPTION
**Pull request by youwalther65**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bonclay7** [comment]
Linked to https://github.com/aws-observability/terraform-aws-observability-accelerator/pull/208

**Review by bonclay7 — APPROVED** [review]
LGTM, but this might add empty dashboards on CDK, let's sync on this @elamaran11 

Created an issue to split it in another PR https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/210

**Comment by elamaran11** [comment]
@bonclay7 Im good with this PR. But we would need a path on how to make this work for CDK too. Do we need new AMP Rules?

**Review by elamaran11 — APPROVED** [review]
LGTM

**Pull request merged**
